spring:
  application:
    name: chat-bot-service
  datasource:
    url: jdbc:postgresql://localhost:5434/chatbot?stringtype=unspecified
    username: chatbot
    password: chatbot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs
